### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by nothingismagick** [webview/webview_rust#15]
We need to revise this CI to avoid using the stuff from the old Tauri CI.

**Comment by wusyong** [comment]
Would like to know what's current blocker on windows build because I can't reproduce same error in the windows workflow.

**Comment by wusyong** [comment]
Maybe we could skip windows build for now? It looks like it's more like a [main repo issue](https://github.com/webview/webview/pull/396). And then we open another issue about adding windows CI back.

**Comment by wusyong** [comment]
I opened a PR on webview [#414](https://github.com/webview/webview/pull/414). This should finally fix the problem.
