### ISSUE TITLE
Seperate ffi module to a file or even become another `*-sys`

### ISSUE THREAD

**Issue by wusyong** [webview/webview_rust#16]
When creating FFI bindings, we usually will create another `*-sys` crate for the raw binding (which is what ffi module does right now). But I tend to know that it might be tedious to maintain two crates even it's not really necessary. Maybe it's also idiomatic to move it to a standalone file as `sys` module?

**Comment by nothingismagick** [comment]
one of the things we talked about at tauri a while back was making it possible for devs to actually switch out the entire crate - and potentially even the sys bindings with a version they prefer.

**Comment by wusyong** [comment]
In that case, I think it does better to make sys binding in main crate. Maybe we can add some feature flags in the futures. So users just need to switch the flag and get the raw bindings.

**Comment by nothingismagick** [comment]
regarding the feature flags: optimal!

**Comment by nothingismagick** [comment]
This was just brought up at tauri:
https://github.com/tauri-apps/tauri/issues/813
