### ISSUE TITLE
Expose webview-official-sys crate

### ISSUE THREAD

**Issue by notfilippo** [webview/webview_rust#38]
**Is your feature request related to a problem? Please describe.**
We are encountering some issues handling Webview rust wrapper types in a multithreaded environment while creating webview bindings for [webview/webview_deno](https://github.com/webview/webview_deno). We would like to have  more control over the actual c_void pointers that currently are not exposed by the crate. 

**Describe the solution you'd like**
`sys` bindings should be exported from the crate, or be made available in a separate crate.

**Describe alternatives you've considered**
Taking the code that we need directly for this repository, removing the dependency from webview_official (this crate). This approach is feasible but we think that the correct approach is to expose the bindings directly.

CC @eliassjogreen

**Comment by wusyong** [comment]
Let me change title a bit. It does better to have separate sys crate when comes to ffi bindings.
