### ISSUE TITLE
bug: window titles are not showing up in macOS 

### ISSUE THREAD

**Issue by notfilippo** [webview/webview_rust#47]
**Describe the bug**
Titles in the webview window are not showing up in macOS when running examples in this repo.

**To Reproduce**
Run the examples in a macOS machine.

**Expected behavior**
The title "TEST" should appear in the top of this window.

**Screenshots**
Screenshot of window opened with the `sample` example:

<img width="1024" alt="Screenshot 2020-07-31 at 22 38 48" src="https://user-images.githubusercontent.com/12383260/89075492-9c4f3c80-d37e-11ea-8246-b2e903186ea8.png">

**Platform and Versions (please complete the following information):**

OS: 64bit Mac OS X 10.15.6 19G73
Rustc: rustc 1.45.0 (5c1f21c3b 2020-07-13)

**Comment by wusyong** [comment]
Hmm, it can't show the title in original repo either. Maybe we should also file a issue there.
